const fs=require("fs"); const path=require("path"); const Catalog=require("../models/Catalog"); const Media=require("../models/Media"); const {sendSuccess,sendError}=require("../helpers/responseHelper"); const {stripTags,toSlug,parseJsonArray,nullable}=require("../services/catalogService"); const {uploadRoot}=require("../middleware/uploadMiddleware");
function vals(input){return String(input||"").split(",").map((x,i)=>{const label=stripTags(x);return label?{label,slug:toSlug(label),sortOrder:i}:null}).filter(Boolean)}
async function listAttributes(req,res,next){try{sendSuccess(res,{data:await Catalog.listAttributes()})}catch(e){next(e)}}
async function createAttribute(req,res,next){try{const name=stripTags(req.body.name); const id=await Catalog.createAttribute({name,slug:toSlug(req.body.slug||name),inputType:req.body.inputType||"select",isVariant:Boolean(req.body.isVariant),values:Array.isArray(req.body.values)?req.body.values:vals(req.body.values)});sendSuccess(res,{statusCode:201,data:{id}})}catch(e){next(e)}}
async function deleteAttribute(req,res,next){try{sendSuccess(res,{data:{deleted:await Catalog.deleteAttribute(req.params.id)}})}catch(e){next(e)}}
async function listCollections(req,res,next){try{const r=await Catalog.listCollections(req.query);sendSuccess(res,{data:r.rows,meta:r.pagination})}catch(e){next(e)}}
async function createCollection(req,res,next){try{const name=stripTags(req.body.name); const id=await Catalog.createCollection({name,slug:toSlug(req.body.slug||name),description:nullable(req.body.description),status:req.body.status||"active",productIds:parseJsonArray(req.body.productIds,[])},req.user.id);sendSuccess(res,{statusCode:201,data:{id}})}catch(e){next(e)}}
async function deleteCollection(req,res,next){try{sendSuccess(res,{data:{deleted:await Catalog.deleteCollection(req.params.id)}})}catch(e){next(e)}}
async function listMedia(req,res,next){try{const r=await Media.list(req.query);sendSuccess(res,{data:r.rows,meta:r.pagination})}catch(e){next(e)}}
async function uploadMedia(req,res,next){try{if(!req.files?.length)return sendError(res,{statusCode:400,message:"Image required"}); const rows=[]; for(const f of req.files) rows.push(await Media.createFromFile(f,req.user.id,req.body.altText||null)); sendSuccess(res,{statusCode:201,data:rows})}catch(e){next(e)}}
async function deleteMedia(req,res,next){try{const m=await Media.findById(req.params.id); if(!m)return sendError(res,{statusCode:404,message:"Media not found"}); await Media.delete(req.params.id); fs.unlink(path.join(uploadRoot,m.file_name),()=>{}); sendSuccess(res,{message:"Media deleted"})}catch(e){next(e)}}
module.exports={listAttributes,createAttribute,deleteAttribute,listCollections,createCollection,deleteCollection,listMedia,uploadMedia,deleteMedia};
