const { StatusCodes } = require("http-status-codes");
const Product=require("../models/Product"); const Category=require("../models/Category"); const Brand=require("../models/Brand"); const Media=require("../models/Media"); const {sendSuccess,sendError}=require("../helpers/responseHelper"); const {normalizeProductPayload,parseCsv,toSlug,stripTags,toNumber,toInt}=require("../services/catalogService");
function dbError(res,e){if(e.code==="ER_DUP_ENTRY")return sendError(res,{statusCode:409,message:"Duplicate SKU, slug, or variant SKU"}); throw e;}
async function listProducts(req,res,next){try{const r=await Product.list(req.query);return sendSuccess(res,{message:"Products fetched",data:r.rows,meta:r.pagination});}catch(e){next(e)}}
async function getProduct(req,res,next){try{const p=await Product.findById(req.params.id); if(!p)return sendError(res,{statusCode:404,message:"Product not found"}); return sendSuccess(res,{data:p});}catch(e){next(e)}}
async function createProduct(req,res,next){try{const p=await Product.create(normalizeProductPayload(req.body),req.user.id); return sendSuccess(res,{statusCode:201,message:"Product created",data:p});}catch(e){try{return dbError(res,e)}catch(x){next(x)}}}
async function updateProduct(req,res,next){try{const p=await Product.update(req.params.id,normalizeProductPayload(req.body),req.user.id); if(!p)return sendError(res,{statusCode:404,message:"Product not found"}); return sendSuccess(res,{message:"Product updated",data:p});}catch(e){try{return dbError(res,e)}catch(x){next(x)}}}
async function deleteProduct(req,res,next){try{const ok=await Product.delete(req.params.id); if(!ok)return sendError(res,{statusCode:404,message:"Product not found"}); return sendSuccess(res,{message:"Product deleted"});}catch(e){next(e)}}
async function bulkUploadProducts(req,res,next){try{if(!req.file)return sendError(res,{statusCode:400,message:"CSV file required"}); const rows=parseCsv(req.file.buffer.toString("utf8")); const created=[],failed=[]; for(const row of rows){try{const cat=row.category_slug?await Category.findBySlug(toSlug(row.category_slug)):null; const brand=row.brand_slug?await Brand.findBySlug(toSlug(row.brand_slug)):null; const p=await Product.create(normalizeProductPayload({...row,categoryId:cat?.id||row.category_id,brandId:brand?.id||row.brand_id,stockQuantity:row.stock_quantity,seoTitle:row.seo_title,seoDescription:row.seo_description}),req.user.id); created.push({id:p.id,sku:p.sku,title:p.title});}catch(e){failed.push({sku:row.sku,title:row.title,reason:e.code==="ER_DUP_ENTRY"?"Duplicate SKU or slug":e.message})}} return sendSuccess(res,{statusCode:201,message:"Bulk upload processed",data:{created,failed}});}catch(e){next(e)}}
async function uploadProductImages(req,res,next){try{const product=await Product.findById(req.params.id); if(!product)return sendError(res,{statusCode:404,message:"Product not found"}); if(!req.files?.length)return sendError(res,{statusCode:400,message:"Image required"}); const out=[]; for(let i=0;i<req.files.length;i++){const media=await Media.createFromFile(req.files[i],req.user.id,req.body.altText||product.title); await Product.attachMedia(product.id,media.id,{altText:req.body.altText||product.title,sortOrder:i,isPrimary:i===0}); out.push(media)} return sendSuccess(res,{statusCode:201,message:"Images uploaded",data:out});}catch(e){next(e)}}
module.exports={listProducts,getProduct,createProduct,updateProduct,deleteProduct,bulkUploadProducts,uploadProductImages};
