const { pool } = require("../config/database");
const Catalog = {
  async listAttributes(){const [a]=await pool.execute("SELECT * FROM catalog_attributes ORDER BY name"); const [v]=await pool.execute("SELECT * FROM catalog_attribute_values ORDER BY sort_order,value_label"); return a.map(x=>({...x,values:v.filter(y=>String(y.attribute_id)===String(x.id))}));},
  async createAttribute(d){const c=await pool.getConnection(); try{await c.beginTransaction(); const [r]=await c.execute("INSERT INTO catalog_attributes(name,slug,input_type,is_variant,status) VALUES(?,?,?,?,?)",[d.name,d.slug,d.inputType||"select",d.isVariant?1:0,d.status||"active"]); for(const val of d.values||[]) await c.execute("INSERT INTO catalog_attribute_values(attribute_id,value_label,value_slug,color_hex,sort_order) VALUES(?,?,?,?,?)",[r.insertId,val.label,val.slug,val.colorHex||null,val.sortOrder||0]); await c.commit(); return r.insertId;} catch(e){await c.rollback(); throw e;} finally{c.release();}},
  async deleteAttribute(id){const [r]=await pool.execute("DELETE FROM catalog_attributes WHERE id=?",[id]); return r.affectedRows>0;},
  async listCollections({ search="", page=1, limit=50 }={}){const p=[],w=[]; if(search){w.push("(c.name LIKE ? OR c.slug LIKE ?)");p.push(`%${search}%`,`%${search}%`)} const ws=w.length?`WHERE ${w.join(" AND ")}`:""; const l=Math.min(Number(limit)||50,100),o=((Number(page)||1)-1)*l; const [rows]=await pool.execute(`SELECT c.*,COUNT(cp.product_id) product_count FROM catalog_collections c LEFT JOIN catalog_collection_products cp ON cp.collection_id=c.id ${ws} GROUP BY c.id ORDER BY c.created_at DESC LIMIT ? OFFSET ?`,[...p,l,o]); const [cr]=await pool.execute(`SELECT COUNT(*) total FROM catalog_collections c ${ws}`,p); return {rows,pagination:{page:Number(page)||1,limit:l,total:cr[0]?.total||0}};},
  async createCollection(d,adminId){const c=await pool.getConnection(); try{await c.beginTransaction(); const [r]=await c.execute("INSERT INTO catalog_collections(name,slug,description,status,starts_at,ends_at,seo_title,seo_description,created_by) VALUES(?,?,?,?,?,?,?,?,?)",[d.name,d.slug,d.description||null,d.status||"active",d.startsAt||null,d.endsAt||null,d.seoTitle||null,d.seoDescription||null,adminId||null]); for(const pid of d.productIds||[]) await c.execute("INSERT IGNORE INTO catalog_collection_products(collection_id,product_id) VALUES(?,?)",[r.insertId,pid]); await c.commit(); return r.insertId;} catch(e){await c.rollback(); throw e;} finally{c.release();}},
  async deleteCollection(id){const [r]=await pool.execute("DELETE FROM catalog_collections WHERE id=?",[id]); return r.affectedRows>0;}
}; module.exports=Catalog;
