const { pool } = require("../config/database");
const Category = {
  async list({ search="", status="", page=1, limit=100 }={}) { const where=[]; const p=[]; if(search){where.push("(name LIKE ? OR slug LIKE ?)");p.push(`%${search}%`,`%${search}%`)} if(status){where.push("status=?");p.push(status)} const ws=where.length?`WHERE ${where.join(" AND ")}`:""; const l=Math.min(Number(limit)||100,100), o=((Number(page)||1)-1)*l; const [rows]=await pool.execute(`SELECT c.*, COUNT(pr.id) product_count FROM catalog_categories c LEFT JOIN catalog_products pr ON pr.category_id=c.id ${ws} GROUP BY c.id ORDER BY sort_order,name LIMIT ? OFFSET ?`,[...p,l,o]); const [cr]=await pool.execute(`SELECT COUNT(*) total FROM catalog_categories ${ws}`,p); return { rows, pagination:{page:Number(page)||1,limit:l,total:cr[0]?.total||0} }; },
  async findById(id){const [r]=await pool.execute("SELECT * FROM catalog_categories WHERE id=?",[id]); return r[0]||null;},
  async findBySlug(slug){const [r]=await pool.execute("SELECT * FROM catalog_categories WHERE slug=?",[slug]); return r[0]||null;},
  async create(d,adminId){const [r]=await pool.execute("INSERT INTO catalog_categories(parent_id,name,slug,description,image_url,seo_title,seo_description,status,sort_order,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)",[d.parentId||null,d.name,d.slug,d.description||null,d.imageUrl||null,d.seoTitle||null,d.seoDescription||null,d.status||"active",d.sortOrder||0,adminId||null]); return this.findById(r.insertId);},
  async update(id,d){await pool.execute("UPDATE catalog_categories SET parent_id=?,name=?,slug=?,description=?,image_url=?,seo_title=?,seo_description=?,status=?,sort_order=? WHERE id=?",[d.parentId||null,d.name,d.slug,d.description||null,d.imageUrl||null,d.seoTitle||null,d.seoDescription||null,d.status||"active",d.sortOrder||0,id]); return this.findById(id);},
  async delete(id){const [r]=await pool.execute("DELETE FROM catalog_categories WHERE id=?",[id]); return r.affectedRows>0;}
}; module.exports=Category;
