const { pool } = require("../config/database");
async function replaceVariants(conn, productId, variants=[]) { await conn.execute("DELETE FROM catalog_product_variants WHERE product_id=?",[productId]); for (const v of variants) await conn.execute("INSERT INTO catalog_product_variants(product_id,variant_sku,option_name,option_value,price,stock_quantity,status) VALUES(?,?,?,?,?,?,?)",[productId,v.variantSku,v.optionName,v.optionValue,v.price,v.stockQuantity,v.status||"active"]); }
const Product = {
  async list(f={}) { const where=[], p=[]; const limit=Math.min(Number(f.limit)||20,100), page=Number(f.page)||1, offset=(page-1)*limit; if(f.search){where.push("(p.title LIKE ? OR p.sku LIKE ? OR p.slug LIKE ?)");p.push(`%${f.search}%`,`%${f.search}%`,`%${f.search}%`)} if(f.status){where.push("p.status=?");p.push(f.status)} if(f.categoryId){where.push("p.category_id=?");p.push(f.categoryId)} if(f.brandId){where.push("p.brand_id=?");p.push(f.brandId)} if(f.stock==="low") where.push("p.track_inventory=1 AND p.stock_quantity<=p.low_stock_threshold"); const ws=where.length?`WHERE ${where.join(" AND ")}`:""; const sort={title:"p.title ASC",price_high:"p.price DESC",price_low:"p.price ASC",stock_low:"p.stock_quantity ASC",oldest:"p.created_at ASC"}[f.sort]||"p.created_at DESC"; const [rows]=await pool.execute(`SELECT p.*,c.name category_name,b.name brand_name,(SELECT COUNT(*) FROM catalog_product_variants v WHERE v.product_id=p.id) variant_count FROM catalog_products p LEFT JOIN catalog_categories c ON c.id=p.category_id LEFT JOIN catalog_brands b ON b.id=p.brand_id ${ws} ORDER BY ${sort} LIMIT ? OFFSET ?`,[...p,limit,offset]); const [cr]=await pool.execute(`SELECT COUNT(*) total FROM catalog_products p ${ws}`,p); return { rows, pagination:{page,limit,total:cr[0]?.total||0} }; },
  async findById(id){const [r]=await pool.execute("SELECT p.*,c.name category_name,b.name brand_name FROM catalog_products p LEFT JOIN catalog_categories c ON c.id=p.category_id LEFT JOIN catalog_brands b ON b.id=p.brand_id WHERE p.id=?",[id]); const product=r[0]; if(!product) return null; const [variants]=await pool.execute("SELECT * FROM catalog_product_variants WHERE product_id=? ORDER BY id",[id]); const [images]=await pool.execute("SELECT pi.*,m.url,m.original_name FROM catalog_product_images pi JOIN catalog_media_assets m ON m.id=pi.media_id WHERE pi.product_id=? ORDER BY is_primary DESC, sort_order",[id]); return {...product,variants,images};},
  async create(d,adminId){const c=await pool.getConnection(); try{await c.beginTransaction(); const [r]=await c.execute("INSERT INTO catalog_products(category_id,brand_id,title,slug,sku,short_description,description,status,product_type,price,compare_at_price,cost_price,currency,stock_quantity,low_stock_threshold,track_inventory,scheduled_at,seo_title,seo_description,seo_keywords,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[d.categoryId||null,d.brandId||null,d.title,d.slug,d.sku,d.shortDescription,d.description,d.status,d.productType,d.price,d.compareAtPrice,d.costPrice,d.currency,d.stockQuantity,d.lowStockThreshold,d.trackInventory?1:0,d.scheduledAt||null,d.seoTitle,d.seoDescription,d.seoKeywords,adminId||null,adminId||null]); await replaceVariants(c,r.insertId,d.variants); await c.commit(); return this.findById(r.insertId);} catch(e){await c.rollback(); throw e;} finally{c.release();}},
  async update(id,d,adminId){const c=await pool.getConnection(); try{await c.beginTransaction(); await c.execute("UPDATE catalog_products SET category_id=?,brand_id=?,title=?,slug=?,sku=?,short_description=?,description=?,status=?,product_type=?,price=?,compare_at_price=?,cost_price=?,currency=?,stock_quantity=?,low_stock_threshold=?,track_inventory=?,scheduled_at=?,seo_title=?,seo_description=?,seo_keywords=?,updated_by=? WHERE id=?",[d.categoryId||null,d.brandId||null,d.title,d.slug,d.sku,d.shortDescription,d.description,d.status,d.productType,d.price,d.compareAtPrice,d.costPrice,d.currency,d.stockQuantity,d.lowStockThreshold,d.trackInventory?1:0,d.scheduledAt||null,d.seoTitle,d.seoDescription,d.seoKeywords,adminId||null,id]); await replaceVariants(c,id,d.variants||[]); await c.commit(); return this.findById(id);} catch(e){await c.rollback(); throw e;} finally{c.release();}},
  async delete(id){const [r]=await pool.execute("DELETE FROM catalog_products WHERE id=?",[id]); return r.affectedRows>0;},
  async attachMedia(productId,mediaId,{altText=null,sortOrder=0,isPrimary=false}={}){ if(isPrimary) await pool.execute("UPDATE catalog_product_images SET is_primary=0 WHERE product_id=?",[productId]); const [r]=await pool.execute("INSERT INTO catalog_product_images(product_id,media_id,alt_text,sort_order,is_primary) VALUES(?,?,?,?,?)",[productId,mediaId,altText,sortOrder,isPrimary?1:0]); return r.insertId; }
}; module.exports=Product;
