const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  CATALOG_VIEW: "catalog.view",
  CATALOG_MANAGE: "catalog.manage",
  ORDERS_VIEW: "orders.view",
  INVENTORY_VIEW: "inventory.view",
  CUSTOMERS_VIEW: "customers.view",
  PAYMENTS_VIEW: "payments.view",
  SHIPPING_MANAGE: "shipping.manage",
  MARKETING_MANAGE: "marketing.manage",
  ANALYTICS_VIEW: "analytics.view",
  STAFF_MANAGE: "staff.manage",
  SECURITY_MANAGE: "security.manage",
  SETTINGS_MANAGE: "settings.manage",
  LOGS_VIEW: "logs.view"
};
const ROLE_PERMISSION_MATRIX = {
  "Super Admin": Object.values(PERMISSIONS),
  Manager: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CATALOG_VIEW, PERMISSIONS.CATALOG_MANAGE, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.ANALYTICS_VIEW, PERMISSIONS.LOGS_VIEW],
  "Shipping Staff": [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.SHIPPING_MANAGE],
  "Marketing Staff": [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.CATALOG_VIEW, PERMISSIONS.CATALOG_MANAGE, PERMISSIONS.MARKETING_MANAGE, PERMISSIONS.ANALYTICS_VIEW],
  "Customer Support": [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.CUSTOMERS_VIEW]
};
module.exports = { PERMISSIONS, ROLE_PERMISSION_MATRIX };
